// Single source of truth for the course map. Run `node tools/curriculum.mjs` to regenerate content/manifest.js.
// Each lesson: [id, zh title, en title, difficulty 1–3, personas]. Stage codes (0.1, 5.5 …) come from the order here.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const B = "beginner", T = "trader", H = "hedger", Q = "quant";
const ALL = [B, T, H, Q];

const TIERS = [
  ["intro", "入门层 · 看懂期权", "Beginner · Reading Options", "#3E97C9", "从一张合约到一张损益图：零基础也能读懂期权在做什么。", "From one contract to one payoff diagram — what options do, from zero."],
  ["core", "原理层 · 定价、波动率与希腊字母", "Principles · Pricing, Volatility & the Greeks", "#1C7FB0", "期权为什么值这个价：无套利、二叉树、Black-Scholes、波动率与希腊字母。", "Why an option costs what it costs: no-arbitrage, trees, Black-Scholes, volatility and the Greeks."],
  ["systems", "策略层 · 策略与风险管理", "Strategy · Strategies & Risk Management", "#155E86", "把形状拼成策略，再把一本期权账管起来。", "Assemble shapes into strategies, then run a book of them."],
  ["markets", "市场层 · 市场结构与线性衍生品", "Markets · Market Structure & Linear Derivatives", "#23845F", "谁在你的对面、0DTE 与加密期权，以及期货与永续这对“线性表亲”。", "Who is on the other side, 0DTE and crypto options, and the linear cousins: futures and perps."],
  ["mastery", "精通层 · 量化、AI 与实战", "Mastery · Quant, AI & Practice", "#6A5ACD", "数值定价、随机波动率、回测、AI 与一笔真实交易的全流程。", "Numerical pricing, stochastic vol, backtesting, AI — and a real trade end to end."],
];

const STAGES = [
  [0, "intro", "为什么需要期权", "Why Options Exist",
    "期权是什么 · 衍生品 · 保险、杠杆与收入 · 线性与凸性",
    "What an option is · Derivatives · Insurance, leverage & income · Linear vs convex",
    "一张“可以不履行”的合约，为什么值钱？", "Why is a contract you may walk away from worth paying for?",
    [["welcome", "期权是什么：一张给未来留余地的合约", "What an Option Is: A Contract That Keeps Your Choices Open", 1, ALL],
     ["derivatives", "衍生品：写在价格上的合约", "Derivatives: Contracts Written on a Price", 1, ALL],
     ["why-options", "人们为什么用期权：保险、杠杆、收入与可能性", "Why People Use Options: Insurance, Leverage, Income & Optionality", 1, ALL],
     ["linear-vs-convex", "线性与凸性：期权、股票与期货的根本区别", "Linear vs Convex: What Really Separates Options, Stocks & Futures", 1, ALL]]],
  [1, "intro", "期权的解剖", "Anatomy of an Option",
    "看涨 · 看跌 · 合约规格与 ×100 · 实值/虚值 · 内在价值与时间价值 · 四个基本头寸",
    "Calls · Puts · Contract specs & ×100 · Moneyness · Intrinsic vs time value · The four basic positions",
    "一张期权合约上到底写了什么？", "What exactly is written on an option contract?",
    [["call-option", "看涨期权：买入的权利", "The Call: The Right to Buy", 1, ALL],
     ["put-option", "看跌期权：卖出的权利", "The Put: The Right to Sell", 1, ALL],
     ["contract-specs", "合约规格：行权价、到期日、权利金与 ×100 乘数", "Contract Specs: Strike, Expiry, Premium & the ×100 Multiplier", 1, ALL],
     ["moneyness", "实值、平值、虚值：期权离“有价值”有多远", "ITM, ATM, OTM: How Far an Option Is From Paying", 1, ALL],
     ["intrinsic-time-value", "内在价值与时间价值：权利金的两块", "Intrinsic vs Time Value: The Two Pieces of a Premium", 1, ALL],
     ["four-positions", "四个基本头寸：买方与卖方互为镜像", "The Four Basic Positions: Buyers and Sellers as Mirror Images", 1, ALL]]],
  [2, "intro", "损益图：期权的语言", "Payoff Diagrams: The Language of Options",
    "曲棍球杆 · 盈亏平衡与收益率 · 积木式叠加 · 到期前的曲线 · 概率与期望值",
    "Hockey sticks · Breakeven & return · Adding payoffs like Lego · The curve before expiry · Probability & expected value",
    "一张图怎样说清一笔期权交易的全部结局？", "How can one picture show every possible outcome of a trade?",
    [["payoff-diagrams", "读懂损益图：曲棍球杆的形状", "Reading Payoff Diagrams: The Hockey Stick", 1, ALL],
     ["breakeven-returns", "盈亏平衡、最大盈亏与收益率", "Breakeven, Max Profit, Max Loss & Return on Risk", 1, [B, T, H]],
     ["payoff-lego", "损益积木：把头寸加在一起", "Payoff Lego: Adding Positions Together", 1, ALL],
     ["before-expiry", "到期前与到期时：为什么今天的曲线是弯的", "Before vs At Expiry: Why Today's Curve Is Curved", 2, ALL],
     ["probability-ev", "概率与期望值：便宜的虚值期权为什么并不便宜", "Probability & Expected Value: Why Cheap OTM Options Aren't Cheap", 2, ALL]]],
  [3, "intro", "市场与交易机制", "Markets & Mechanics",
    "期权链 · 买卖价差与流动性 · 下单 · 行权与指派 · 保证金与权限 · 产品地图",
    "The chain · Spreads & liquidity · Orders · Exercise & assignment · Margin & approval · The product map",
    "从看到报价到成交、行权，中间发生了什么？", "What happens between seeing a quote and exercising a contract?",
    [["option-chain", "读懂期权链：一张报价表里的全部信息", "Reading the Option Chain: Everything on One Quote Board", 1, [B, T, H]],
     ["liquidity-spreads", "买卖价差、成交量与未平仓量：流动性的三个读数", "Bid-Ask, Volume & Open Interest: Reading Liquidity", 1, [B, T, H]],
     ["orders", "下单：开仓与平仓、限价单与多腿组合单", "Placing Orders: Open vs Close, Limit Orders & Multi-Leg Tickets", 1, [B, T, H]],
     ["exercise-assignment", "行权、指派与到期日：美式、欧式、现金与实物交割", "Exercise, Assignment & Expiration Day: American, European, Cash & Physical", 2, ALL],
     ["margin-approval", "保证金与交易权限：谁能卖期权、要押多少钱", "Margin & Approval Levels: Who Can Sell Options and What It Ties Up", 2, [T, H]],
     ["product-map", "产品地图：个股、ETF、指数、0DTE 与加密期权", "The Product Map: Stock, ETF, Index, 0DTE & Crypto Options", 1, ALL]]],

  [4, "core", "无套利：不用模型也能定价", "No-Arbitrage: Pricing Without a Model",
    "六个驱动因素 · 价格边界 · 远期与持有成本 · 看跌看涨平价 · 合成与箱式价差",
    "The six drivers · Price bounds · Forwards & carry · Put-call parity · Synthetics & box spreads",
    "不假设任何模型，我们能对期权价格说出什么？", "Without any model at all, what can we say about an option's price?",
    [["price-drivers", "决定权利金的六个因素", "The Six Drivers of an Option's Price", 1, ALL],
     ["arbitrage-bounds", "价格的边界：期权最贵能多贵、最便宜能多便宜", "Arbitrage Bounds: How Expensive or Cheap an Option Can Be", 2, [T, Q]],
     ["forwards-carry", "远期价格与持有成本：期权定价的锚", "Forward Price & Cost of Carry: The Anchor of Option Pricing", 2, [T, H, Q]],
     ["put-call-parity", "看跌看涨平价：期权世界的守恒律", "Put-Call Parity: The Conservation Law of Options", 2, ALL],
     ["synthetics-boxes", "合成头寸、转换与箱式价差", "Synthetics, Conversions & Box Spreads", 3, [T, Q]]]],
  [5, "core", "从二叉树到 Black-Scholes", "From Binomial Trees to Black-Scholes",
    "一步复制 · 风险中性 · 多步树与美式 · 随机游走与 √T · BS 公式 · 假设与破绽",
    "One-step replication · Risk-neutral pricing · Multi-step trees & American · Random walks & √T · The formula · Where it breaks",
    "一个“公平价”是怎样被算出来的？", "How is a 'fair price' actually computed?",
    [["binomial-one-step", "一步二叉树：复制与对冲比率", "The One-Step Binomial: Replication & the Hedge Ratio", 2, ALL],
     ["risk-neutral", "风险中性定价：最常被误解的一个想法", "Risk-Neutral Pricing: The Most Misunderstood Idea", 3, [T, Q]],
     ["binomial-trees", "多步二叉树与美式期权", "Multi-Step Trees & American Options", 2, [T, Q]],
     ["random-walk", "随机游走、对数正态与 √T 法则", "Random Walks, Lognormal Prices & the √T Rule", 2, ALL],
     ["black-scholes", "Black-Scholes 公式：逐项读懂", "The Black-Scholes Formula, Term by Term", 3, ALL],
     ["bs-assumptions", "Black-Scholes 的假设与破绽", "Black-Scholes: The Assumptions and Where They Break", 3, [T, Q]]]],
  [6, "core", "波动率", "Volatility",
    "历史波动率 · 隐含波动率 · 微笑与偏斜 · 期限结构与曲面 · 价格里的概率 · VIX",
    "Realized vol · Implied vol · Smile & skew · Term structure & surface · Probabilities in prices · The VIX",
    "期权真正在买卖的那个东西，怎么量、怎么读？", "How do we measure and read the thing options really trade?",
    [["realized-vol", "历史波动率：怎么量“晃得有多厉害”", "Realized Volatility: Measuring How Much Prices Move", 2, ALL],
     ["implied-vol", "隐含波动率：用波动率给期权报价", "Implied Volatility: Quoting Options in Vol", 2, ALL],
     ["smile-skew", "波动率微笑与偏斜", "The Volatility Smile & Skew", 3, [T, H, Q]],
     ["term-structure", "期限结构、事件波动率与波动率曲面", "Term Structure, Event Vol & the Vol Surface", 3, [T, Q]],
     ["risk-neutral-density", "期权价格里藏着的概率分布", "The Probabilities Hidden in Option Prices", 3, [T, Q]],
     ["vix", "VIX 与波动率家族", "The VIX & the Volatility Complex", 2, ALL]]],
  [7, "core", "希腊字母", "The Greeks",
    "泰勒展开总览 · Delta · Gamma · Theta · Vega · Rho 与持有成本 · 二阶与组合希腊",
    "The Taylor map · Delta · Gamma · Theta · Vega · Rho & carry · Second-order & portfolio Greeks",
    "价格、时间、波动率各动一点，我的期权会怎样？", "If price, time and volatility each move a little, what happens to my option?",
    [["greeks-map", "希腊字母总览：期权盈亏的泰勒展开", "The Greeks Map: A Taylor Expansion of Option P&L", 2, ALL],
     ["delta", "Delta：方向、对冲比率与“概率”", "Delta: Direction, Hedge Ratio & 'Probability'", 2, ALL],
     ["gamma", "Gamma：Delta 的加速度", "Gamma: The Acceleration of Delta", 2, ALL],
     ["theta", "Theta：时间衰减与 Gamma 的账单", "Theta: Time Decay and the Bill for Gamma", 2, ALL],
     ["vega", "Vega：你其实在交易波动率", "Vega: You're Really Trading Volatility", 2, [T, H, Q]],
     ["rho-carry", "Rho、股息与持有成本", "Rho, Dividends & Carry", 3, [T, Q]],
     ["higher-order-greeks", "二阶希腊与组合希腊：Vanna、Volga、Charm", "Second-Order & Portfolio Greeks: Vanna, Volga, Charm", 3, [T, Q]]]],

  [8, "systems", "方向与收入策略", "Directional & Income Strategies",
    "买入期权 · 备兑看涨 · 现金担保看跌与轮动 · 保护性看跌与领口 · 垂直价差 · 策略地图",
    "Long options · Covered calls · Cash-secured puts & the wheel · Protective puts & collars · Verticals · The strategy map",
    "有了一个观点，用哪种形状去表达它？", "Once you have a view, which shape expresses it best?",
    [["long-options", "买入看涨与看跌：怎么选行权价和到期日", "Long Calls & Puts: Choosing the Strike and the Expiry", 1, [B, T]],
     ["covered-call", "备兑看涨：用持股“收租”", "Covered Calls: Renting Out Your Shares", 1, [B, T, H]],
     ["cash-secured-put", "现金担保看跌与轮动策略", "Cash-Secured Puts & the Wheel", 2, [B, T, H]],
     ["protective-put-collar", "保护性看跌与领口：给持仓买保险", "Protective Puts & Collars: Insuring a Position", 2, [B, H]],
     ["vertical-spreads", "垂直价差：借记与贷记", "Vertical Spreads: Debit and Credit", 2, [T, H]],
     ["strategy-matrix", "策略地图：方向 × 波动率 × 时间", "The Strategy Map: Direction × Volatility × Time", 2, ALL]]],
  [9, "systems", "波动率与时间策略", "Volatility & Time Strategies",
    "跨式 · 铁鹰 · 蝶式 · 日历与对角 · 比率与风险逆转 · 财报与事件",
    "Straddles · Iron condors · Butterflies · Calendars & diagonals · Ratios & risk reversals · Earnings & events",
    "不押方向，只押“动多少”和“什么时候动”，行不行？", "Can you trade how much and when a price moves, without betting on direction?",
    [["straddle-strangle", "跨式与宽跨式：押“会大动”", "Straddles & Strangles: Betting on a Big Move", 2, [T, Q]],
     ["iron-condor", "铁鹰与卖出宽跨：把一个区间租出去", "Iron Condors & Short Strangles: Renting Out a Range", 2, [T, H]],
     ["butterfly", "蝶式：押价格停在哪里", "Butterflies: Betting on Where Price Lands", 3, [T, Q]],
     ["calendar-diagonal", "日历与对角价差：交易期限结构", "Calendars & Diagonals: Trading the Term Structure", 3, [T, Q]],
     ["ratios-risk-reversals", "比率价差、反向价差与风险逆转：交易偏斜", "Ratios, Backspreads & Risk Reversals: Trading the Skew", 3, [T, Q]],
     ["earnings-events", "财报与事件交易：隐含波动率崩塌", "Trading Earnings & Events: The IV Crush", 2, [T, Q]]]],
  [10, "systems", "管理一本期权账", "Running an Options Book",
    "仓位与凯利 · Delta 对冲与 Gamma 剥头皮 · 方差风险溢价 · 尾部对冲 · 组合风险与压力测试 · 心理与纪律",
    "Sizing & Kelly · Delta hedging & gamma scalping · The variance risk premium · Tail hedging · Portfolio risk & stress tests · Psychology",
    "单笔交易之外，怎样活得久？", "Beyond single trades — how do you survive long enough to win?",
    [["position-sizing", "仓位管理、凯利公式与破产风险", "Position Sizing, the Kelly Criterion & Risk of Ruin", 2, [T, H, Q]],
     ["delta-hedging", "Delta 对冲与 Gamma 剥头皮", "Delta Hedging & Gamma Scalping", 3, [T, Q]],
     ["variance-risk-premium", "方差风险溢价：卖波动率为什么赚钱，又为什么会爆", "The Variance Risk Premium: Why Selling Vol Pays — and Blows Up", 3, [T, H, Q]],
     ["tail-hedging", "尾部风险与尾部对冲", "Tail Risk & Tail Hedging", 3, [H, Q]],
     ["portfolio-risk", "组合风险：情景矩阵、压力测试与保证金", "Portfolio Risk: Scenario Grids, Stress Tests & Margin", 3, [T, H, Q]],
     ["trading-psychology", "心理、纪律与交易日志", "Psychology, Discipline & the Trade Journal", 1, [B, T, H]]]],

  [11, "markets", "市场结构：谁在你的对面", "Market Structure: Who's on the Other Side",
    "做市商 · 做市商 Gamma 与钉住 · 0DTE · 散户浪潮与收益型 ETF · 加密期权",
    "Market makers · Dealer gamma & pinning · 0DTE · The retail wave & income ETFs · Crypto options",
    "你每买一张期权，是谁卖给你的？他们接下来会做什么？", "Every time you buy an option, who sold it — and what do they do next?",
    [["market-makers", "做市商：报价、库存与对冲", "Market Makers: Quoting, Inventory & Hedging", 2, [T, Q]],
     ["dealer-gamma", "做市商 Gamma：GEX、钉住效应与期权到期日", "Dealer Gamma: GEX, Pinning & OPEX", 3, [T, Q]],
     ["zero-dte", "0DTE：当天到期的期权成为主流", "0DTE: When Same-Day Options Became the Tape", 2, ALL],
     ["retail-flows", "散户浪潮、Gamma 挤压与期权收益型 ETF", "The Retail Wave, Gamma Squeezes & Option-Income ETFs", 2, [B, T, H]],
     ["crypto-options", "加密期权：Deribit、IBIT 期权与 24/7 的波动率", "Crypto Options: Deribit, IBIT Options & Round-the-Clock Vol", 2, ALL]]],
  [12, "markets", "线性表亲：期货与永续合约", "The Linear Cousins: Futures & Perpetuals",
    "期货与基差 · 永续是什么 · 指数/标记/最新价 · 资金费率 · 保证金与强平 · 保险基金与 ADL · 基差交易 · 永续 vs 期权",
    "Futures & basis · What a perp is · Index, mark & last · Funding · Margin & liquidation · Insurance fund & ADL · Basis trades · Perps vs options",
    "没有凸性的衍生品，靠什么机制运转？又在哪里会咬人？", "How do derivatives without convexity work — and where do they bite?",
    [["futures-basis", "期货与基差：升水、贴水与展期", "Futures & the Basis: Contango, Backwardation & the Roll", 2, ALL],
     ["what-is-perp", "永续合约：一份没有到期日的期货", "Perpetual Futures: A Future With No Expiry", 1, ALL],
     ["mark-index-last", "指数价、标记价、最新价：谁说了算", "Index, Mark & Last Price: Which One Counts", 2, [T, Q]],
     ["funding-rate", "资金费率：把永续拴在现货上的绳子", "Funding: The Tether That Ties Perps to Spot", 2, ALL],
     ["margin-liquidation", "保证金与强平：逐仓、全仓与维持保证金", "Margin & Liquidation: Isolated, Cross & Maintenance", 2, ALL],
     ["insurance-adl", "保险基金与自动减仓（ADL）：穿仓以后谁买单", "The Insurance Fund & Auto-Deleveraging: Who Pays After a Bankruptcy", 3, [T, H, Q]],
     ["basis-trades", "基差与资金费套利：现货对冲的“收租”交易", "Basis & Funding Trades: Cash-and-Carry", 3, [T, Q]],
     ["perps-vs-options", "永续与期权：线性、凸性与常见陷阱", "Perps vs Options: Linear, Convex & the Common Traps", 2, ALL]]],

  [13, "mastery", "量化定价", "Quantitative Pricing",
    "蒙特卡洛 · PDE 与有限差分 · 美式与提前行权 · 奇异期权 · 随机与局部波动率 · 曲面校准",
    "Monte Carlo · PDEs & finite differences · American exercise · Exotics · Stochastic & local vol · Surface calibration",
    "当公式不够用时，怎样给任意期权定价？", "When no closed-form formula exists, how do you price anything?",
    [["monte-carlo", "蒙特卡洛定价：用模拟给期权估值", "Monte Carlo Pricing: Valuing by Simulation", 3, [Q]],
     ["finite-difference", "PDE 与有限差分：另一条定价之路", "The PDE & Finite Differences: The Other Road to a Price", 3, [Q]],
     ["american-exercise", "美式期权与提前行权：什么时候该提前", "American Options & Early Exercise: When to Go Early", 3, [T, Q]],
     ["exotic-options", "奇异期权：障碍、亚式、数字与回望", "Exotic Options: Barrier, Asian, Digital & Lookback", 3, [H, Q]],
     ["stochastic-vol", "随机波动率与局部波动率：Heston、Dupire、SABR 与粗糙波动率", "Stochastic & Local Vol: Heston, Dupire, SABR & Rough Vol", 3, [Q]],
     ["surface-calibration", "构建无套利的波动率曲面：SVI 与校准", "Building an Arbitrage-Free Vol Surface: SVI & Calibration", 3, [Q]]]],
  [14, "mastery", "量化交易与研究", "Quant Trading & Research",
    "期权数据 · 回测的坑 · 系统化波动率策略 · 波动率预测 · 执行与交易成本",
    "Options data · Backtesting pitfalls · Systematic vol strategies · Vol forecasting · Execution & costs",
    "一个想法，怎样变成能被检验、能执行的策略？", "How does an idea become a strategy you can test and execute?",
    [["options-data", "期权数据：从原始报价到干净的曲面", "Options Data: From Raw Quotes to a Clean Surface", 3, [Q]],
     ["backtesting", "期权策略回测：那些坑", "Backtesting Options Strategies: The Pitfalls", 3, [T, Q]],
     ["systematic-vol", "系统化波动率策略：卖权指数、离散度与偏斜交易", "Systematic Vol Strategies: Put-Writing, Dispersion & Skew", 3, [T, Q]],
     ["vol-forecasting", "波动率预测：GARCH、HAR 与机器学习", "Volatility Forecasting: GARCH, HAR & Machine Learning", 3, [Q]],
     ["execution-tca", "算法执行、滑点与交易成本分析", "Execution, Slippage & Transaction-Cost Analysis", 3, [T, Q]]]],
  [15, "mastery", "AI 时代的期权", "Options in the AI Era",
    "深度对冲 · 神经网络定价与校准 · 强化学习做市 · LLM 与另类数据 · 智能体与护栏",
    "Deep hedging · Neural pricing & calibration · RL market making · LLMs & alt data · Agents with guardrails",
    "机器学习和 AI 智能体，真正改变了期权世界的哪些部分？", "What have machine learning and AI agents actually changed in options?",
    [["deep-hedging", "深度对冲：让神经网络学会对冲", "Deep Hedging: Teaching a Network to Hedge", 3, [Q]],
     ["neural-pricing", "神经网络定价与深度校准", "Neural Pricing & Deep Calibration", 3, [Q]],
     ["rl-market-making", "强化学习：做市与最优执行", "Reinforcement Learning for Market Making & Execution", 3, [Q]],
     ["llm-signals", "LLM、新闻与另类数据信号", "LLMs, News & Alternative-Data Signals", 2, [T, Q]],
     ["ai-agents", "AI 智能体：研究、编码与执行，以及它们的护栏", "AI Agents: Research, Code & Execution — With Guardrails", 2, ALL]]],
  [16, "mastery", "动手实战", "Hands-On",
    "券商与平台 · 一笔真实交易 · Python 定价 · Python 回测 · 常见陷阱 · 毕业项目 · 速查表",
    "Brokers & platforms · A real trade · Python pricing · Python backtest · Common traps · Capstone · Cheat sheet",
    "把整条路走通：从一个观点，到一笔被认真管理的交易。", "Walk the whole path: from a view to a well-managed trade.",
    [["broker-platform", "选择券商与交易平台", "Choosing a Broker & Trading Platform", 1, [B, T, H]],
     ["first-trade", "一笔真实交易的全流程", "A Real Trade, End to End", 2, [B, T, H]],
     ["python-pricing", "用 Python 定价、画希腊字母", "Pricing & Plotting the Greeks in Python", 3, [Q]],
     ["python-backtest", "用 Python 构建并回测一个期权策略", "Build & Backtest an Options Strategy in Python", 3, [T, Q]],
     ["common-traps", "常见陷阱：指派、钉住、流动性、股息与财报", "Common Traps: Assignment, Pin Risk, Liquidity, Dividends & Earnings", 2, [B, T, H]],
     ["capstone", "毕业项目：从一个观点到一笔完整的交易", "Capstone: From a View to a Complete Trade", 3, ALL],
     ["cheat-sheet", "附录：公式与数字速查表", "Appendix: Formula & Numbers Cheat Sheet", 1, ALL]]],
];

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const q = (s) => JSON.stringify(s);
let out = `// Course map — GENERATED by tools/curriculum.mjs (edit that file, then run: node tools/curriculum.mjs).
// Lessons live in content/lessons/zh/<id>.md and content/lessons/en/<id>.md (format: AUTHORING.md).
// difficulty: 1 basic · 2 intermediate · 3 advanced. personas: which learning goals the lesson matters most for.

export const COURSE = {
  title: "Droplet Labs · 期权之路",
  titleEn: "Droplet Labs · Options Path",
  subtitle: "从零到专家，真正吃透期权：它们在做什么、为什么值这个价、怎样用它们表达观点和管理风险——以及 0DTE、加密期权、永续与 AI 的今天。",
  subtitleEn: "From zero to expert — really understand options: what they do, why they cost what they cost, how to express a view and manage the risk — and today's world of 0DTE, crypto options, perps and AI.",
  goals: [
    { id: "beginner", label: "新手", labelEn: "Newcomer" },
    { id: "trader", label: "交易者", labelEn: "Trader" },
    { id: "hedger", label: "投资与对冲", labelEn: "Investor / Hedger" },
    { id: "quant", label: "量化与开发", labelEn: "Quant / Dev" },
  ],
  tiers: [
${TIERS.map(([id, l, le, c, b, be]) => `    { id: ${q(id)}, label: ${q(l)}, labelEn: ${q(le)}, color: ${q(c)}, blurb: ${q(b)}, blurbEn: ${q(be)} },`).join("\n")}
  ],
  stages: [
`;
for (const [n, tier, title, titleEn, blurb, blurbEn, question, questionEn, lessons] of STAGES) {
  out += `    {
      n: ${n}, tier: ${q(tier)}, title: ${q(title)}, titleEn: ${q(titleEn)},
      blurb: ${q(blurb)}, blurbEn: ${q(blurbEn)},
      question: ${q(question)}, questionEn: ${q(questionEn)},
      lessons: [
${lessons.map(([id, t, te, d, p]) => `        { id: ${q(id)}, title: ${q(t)}, titleEn: ${q(te)}, difficulty: ${d}, personas: ${q(p)} },`).join("\n")}
      ],
    },
`;
}
out += `  ],
};
`;
fs.writeFileSync(path.join(ROOT, "content/manifest.js"), out);
const nL = STAGES.reduce((a, s) => a + s[8].length, 0);
const ids = STAGES.flatMap((s) => s[8].map((l) => l[0]));
const dup = ids.filter((x, i) => ids.indexOf(x) !== i);
console.log(`manifest.js written: ${STAGES.length} stages, ${nL} lessons${dup.length ? " · DUPLICATE IDS: " + dup.join(", ") : ""}`);
