// Merge content/glossary-proposals/*.json into content/glossary.js.
//   node tools/merge_glossary.mjs            (writes content/glossary.js; prints a report)
// Rules: proposals win over the existing glossary; entries are de-duplicated by any shared term (zh or en, case-insensitive);
// ASCII double quotes inside definitions are converted to curly quotes; terms shorter than 2 characters are dropped.
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = path.join(ROOT, "content/glossary-proposals");
const old = (await import(pathToFileURL(path.join(ROOT, "content/glossary.js")).href + "?t=" + Date.now())).GLOSSARY;

const clean = (s) => String(s || "").trim().replace(/"([^"]*)"/g, "“$1”").replace(/"/g, "”");
// Terms too generic to underline (they collide with ordinary words or other meanings)
const DENY = { zh: new Set(["期权", "价格", "行权", "分配", "盈亏", "损益", "箱体", "复制", "到期"]), en: new Set(["option", "options", "price", "call", "put", "calls", "puts", "spread", "premium", "roll", "kink", "kinks", "odd", "pop", "carry"]) };
const norm = (e) => ({
  zh: { terms: [...new Set((e.zh?.terms || e.zh?.n || []).map((x) => x.trim()).filter((x) => x.length >= 2 && !DENY.zh.has(x)))], def: clean(e.zh?.def || e.zh?.d) },
  en: { terms: [...new Set((e.en?.terms || e.en?.n || []).map((x) => x.trim()).filter((x) => x.length >= 2 && !DENY.en.has(x.toLowerCase())))], def: clean(e.en?.def || e.en?.d) },
});
const keys = (e) => [...e.zh.terms.map((t) => "zh:" + t), ...e.en.terms.map((t) => "en:" + t.toLowerCase())];

const proposals = [];
for (const f of fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort()) {
  try {
    const arr = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    for (const e of arr) proposals.push({ ...norm(e), src: f });
  } catch (e) { console.log("✗ cannot parse", f, e.message); }
}
const out = [], seen = new Map();
let dup = 0;
function add(e, src) {
  if (!e.zh.terms.length || !e.en.terms.length || !e.zh.def || !e.en.def) return;
  const clash = keys(e).find((k) => seen.has(k));
  if (clash) { dup++; const target = seen.get(clash); // merge extra aliases into the earlier entry
    for (const t of e.zh.terms) if (!seen.has("zh:" + t)) { target.zh.terms.push(t); seen.set("zh:" + t, target); }
    for (const t of e.en.terms) if (!seen.has("en:" + t.toLowerCase())) { target.en.terms.push(t); seen.set("en:" + t.toLowerCase(), target); }
    return; }
  const entry = { zh: e.zh, en: e.en };
  out.push(entry);
  for (const k of keys(e)) seen.set(k, entry);
}
for (const p of proposals) add(p, p.src);
const newCount = out.length;
for (const o of old) add(norm(o), "old");

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const body = out.map((e) => `  {\n    zh: { terms: [${e.zh.terms.map((t) => `"${esc(t)}"`).join(", ")}], def: "${esc(e.zh.def)}" },\n    en: { terms: [${e.en.terms.map((t) => `"${esc(t)}"`).join(", ")}], def: "${esc(e.en.def)}" },\n  },`).join("\n");
fs.writeFileSync(path.join(ROOT, "content/glossary.js"),
`// Bilingual glossary for hover cards. Generated by tools/merge_glossary.mjs from content/glossary-proposals/*.json
// (plus older entries that no proposal replaced). terms = strings to match in lesson text; def = 1–2 sentence definition.
// The first occurrence of any term in a lesson gets a dotted underline and a hover card.

export const GLOSSARY = [
${body}
];
`);
console.log(`${proposals.length} proposed entries · ${newCount} kept from proposals · ${out.length - newCount} carried over from the old glossary · ${dup} duplicates merged → ${out.length} entries`);
